language: go
go:
  - 1.16.2
  -tip
sudo: required
os:
  - linux
  - osx
notifications:
  email: lanliddd.2007@163.com
before_install:
  - go mod tidy

script:
  - echo "run"
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./...
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
